---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  document-start:
    present: true
  line-length:
    max: 140
    level: warning
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    allowed-values:
      - "true"
      - "false"
