---

# tasks file for Work
- name: include base packages
  import_tasks: debian-packages.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - packages

- name: include pip modules
  import_tasks: pip.yml
  tags:
    - pip

- name: include packages from binaries
  import_tasks: binaries.yml
  tags:
    - binaries

- name: Include snap packages
  import_tasks: snap.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - snap

- name: Include npm packages
  import_tasks: npm.yml
  tags:
    - npm
