---

# tasks file for Work
- name: Include base packages
  ansible.builtin.import_tasks: debian-packages.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - packages

- name: Include pip modules
  ansible.builtin.import_tasks: pip.yml
  tags:
    - pip

- name: Include packages from binaries
  ansible.builtin.import_tasks: binaries.yml
  tags:
    - binaries

- name: Include snap packages
  ansible.builtin.import_tasks: snap.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - snap

- name: Include npm packages
  ansible.builtin.import_tasks: npm.yml
  tags:
    - npm
