---
# Install pip modules

- name: PIP | self-update
  ansible.builtin.pip:
    name: pip
    state: latest
  tags:
    - pip

- name: PIP | install packages
  ansible.builtin.pip:
    name:
      - ansible==2.10.4
      - ansible-base==2.10.4
      - awscli==1.18.198
      - boto
      - boto3
      - slackpy
    executable: pip3
    extra_args: --upgrade
  tags:
    - pip
