---
# Install pip modules

- name: PIP | self-update
  ansible.builtin.pip:
    name: pip
    state: present
  tags:
    - pip

- name: PIP | install packages
  ansible.builtin.pip:
    name: "{{ workstation_pip_packages }}"
    executable: pip3
    extra_args: --upgrade
  tags:
    - pip
