---

workstation_terraform_arch: "amd64"
workstation_terraform_system: "linux"
workstation_terraform_version: "1.14.3"
workstation_terraform_file: >-
  terraform_{{ workstation_terraform_version }}_{{ workstation_terraform_system }}_{{ workstation_terraform_arch }}.zip
workstation_terraform_url: "https://releases.hashicorp.com/terraform/{{ workstation_terraform_version }}/{{ workstation_terraform_file }}"
workstation_terraform_checksum: "sha256:178b2a602251bb68b94732aceca2cc1023d87597cb83dba92cab31b6689edb4d"
workstation_terraform_bin_dir: /usr/local/bin
workstation_terraform_bin: "{{ workstation_terraform_bin_dir }}/terraform"
workstation_terraform_path: "/opt/terraform"
workstation_terraform_version_dir: "{{ workstation_terraform_path }}/{{ workstation_terraform_version }}"
workstation_terraform_version_bin: "{{ workstation_terraform_version_dir }}/terraform"

# terragrunt
workstation_terragrunt_arch: "amd64"
workstation_terragrunt_system: "linux"
workstation_terragrunt_version: "0.99.4"
workstation_terragrunt_file: "terragrunt_{{ workstation_terragrunt_system }}_{{ workstation_terragrunt_arch }}"
workstation_terragrunt_url: >-
  {{
    'https://github.com/gruntwork-io/terragrunt/releases/download/v'
    ~ workstation_terragrunt_version
    ~ '/'
    ~ workstation_terragrunt_file
  }}
workstation_terragrunt_bin_dir: /usr/local/bin

# minikube
workstation_minikube_arch: "amd64"
workstation_minikube_version: "v1.37.0"
workstation_minikube_release_version: "v1.37.0-0"
workstation_minikube_file: "minikube_{{ workstation_minikube_release_version }}_{{ workstation_minikube_arch }}.deb"
workstation_minikube_url: >-
  https://github.com/kubernetes/minikube/releases/download/{{ workstation_minikube_version }}/{{ workstation_minikube_file }}

workstation_docker_machine_arch: "amd64"
workstation_docker_machine_version: "v1.12.0"
workstation_docker_machine_release_version: "v1.12.0-0"
workstation_docker_machine_driver_file: >-
  docker-machine-driver-kvm2_{{ workstation_docker_machine_release_version }}_{{ workstation_docker_machine_arch }}.deb
workstation_docker_machine_driver_url: >-
  {{
    'https://github.com/kubernetes/minikube/releases/download/'
    ~ workstation_docker_machine_version
    ~ '/'
    ~ workstation_docker_machine_driver_file
  }}
workstation_docker_machine_driver_checksum: "fabd7a19c8cca563e32321f070311d70404311602e5c9db17b556c0812d1c899"

# helm
workstation_helm_arch: "linux-amd64"
workstation_helm_version: "v3.19.2"
workstation_helm_file: "helm-{{ workstation_helm_version }}-{{ workstation_helm_arch }}.tar.gz"
workstation_helm_folder: "/tmp/{{ workstation_helm_arch }}"
workstation_helm_url: https://get.helm.sh/{{ workstation_helm_file }}
workstation_helm_checksum: 2114c9dea2844dce6d0ee2d792a9aae846be8cf53d5b19dc2988b5a0e8fec26e

# helmfile
workstation_helmfile_arch: linux_amd64
workstation_helmfile_version: v1.1.9
workstation_helmfile_folder: "/tmp/"
workstation_helmfile_file: helmfile_linux_amd64
workstation_helmfile_url: >-
  https://github.com/helmfile/helmfile/releases/download/{{ workstation_helmfile_version }}/{{ workstation_helmfile_file }}

# 1password
workstation_1password_arch: "amd64"
workstation_1password_release_version: "v1.6.0"
workstation_1password_file: "op_linux_{{ workstation_1password_arch }}_{{ workstation_1password_release_version }}.zip"
workstation_1password_url: >-
  https://cache.agilebits.com/dist/1P/op/pkg/{{ workstation_1password_release_version }}/{{ workstation_1password_file }}

# fast node manager
workstation_fnm_version: 1.35.1
workstation_fnm_node_versions:
  - 20.11.1

# mage
workstation_mage_binary_url: https://github.com/magefile/mage/releases/download/v1.15.0/mage_1.15.0_Linux-64bit.tar.gz

# sops - encrypt terraform
workstation_sops_version: 3.11.0
workstation_sops_arch: amd64
workstation_sops_url: >-
  {{
    'https://github.com/getsops/sops/releases/download/v'
    ~ workstation_sops_version
    ~ '/sops_'
    ~ workstation_sops_version
    ~ '_'
    ~ workstation_sops_arch
    ~ '.deb'
  }}
