name: ansible-lint
on:
  push:
    branches: ["master", "stable", "release/v*"]
  pull_request:
    branches: ["master", "stable", "release/v*"]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible-Galaxy Requirements
        run: ansible-galaxy install -r requirements.yml
      - name: List Installed Ansible-Galaxy Requirements
        run: ansible-galaxy collection list
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
