---

- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400 # One day
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - git
    - curl
    - tree
    - neovim
    - net-tools
    - python3-neovim
    - python3-pip
    - openvpn-systemd-resolved
    - remmina
    - flameshot
    - htop
    - nload
    - virtualbox
    - direnv
    - build-essential
    - pgadmin4
    - tmux
    - tmate
    - fonts-powerline
    - xclip
    - openjdk-8-jdk-headless
    - nmap
    - nodejs
    - npm
    - httping


##################
# Install pgadmin4
##################

- name: Add pgadmin key
  apt_key:
    url: "https://www.pgadmin.org/static/packages_pgadmin_org.pub"
    state: present
  tags:
    - pgadmin4

- name: Add pgadmin4 repository
  apt_repository:
    repo: deb [arch=amd64] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/{{ ansible_distribution_release }} pgadmin4 main
    state: present
  tags:
    - pgadmin4

- name: Install pgamdin4
  apt:
    name: pgadmin4
    state: present
  tags:
    - pgadmin4


###################
# Install 1password
###################

- name: Add 1password key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
    keyring: /usr/share/keyrings/1password.gpg
    state: present 
  tags:
    - 1password

- name: Add 1password repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password.gpg] https://downloads.1password.com/linux/debian edge main
    state: present 
  tags:
    - 1password

- name: Install 1password
  apt:
    name: 1password
    state: present 
  tags:
    - 1password

##########################
# Install hashicorp packer
##########################

- name: Add hashicorp apt key
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present
  tags:
    - packer

- name: Add hashicorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    # repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    state: present
  tags:
    - packer

- name: Install hashicorp packer
  apt:
    name: packer
    state: present
  tags:
    - packer

######################################
# Install sublime text / sublime merge
######################################

- name: Add sublimetext apt key
  apt_key:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    state: present
  tags:
    - sublime-text

- name: Add sublimetext repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.sublimetext.com/ apt/stable/"
    state: present
  tags:
    - sublime-text

- name: Install sublimetext & sublime merge
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sublime-text
      - sublime-merge
  tags:
    - sublime-text

################
# Install docker
################

- name: Add docker key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  tags:
    - docker

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  tags:
    - docker

- name: Install docker
  apt:
    name: docker-ce
    state: present
  tags:
    - docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  tags:
    - docker

- name: Add user to docker group
  user:
      name: "{{ lookup('env', 'USER') }}"
      group: docker
      append: true
  tags:
    - docker

#################
# Install kubectl
#################

- name: Add kubectl key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present
  tags:
    - k8s

- name: Add kubectl repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  tags:
    - k8s

- name: Install kubectl
  apt:
    name: kubectl
    state: present
  tags:
    - k8s

##################
# Install minikube
##################

- name: Add kubectl repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  tags:
    - k8s

- name: Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '755'
  tags:
    - k8s

- name: Set minikube permissions
  file:
      path: /usr/local/bin/minikube
      owner: "{{ lookup('env', 'USER') }}"
      group: docker
      mode: '0755'
  tags:
    - k8s
